version: "3.8"

services:
    pgsql:
        container_name: bos.wiki-pgsql
        image: postgis/postgis:latest
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"

    redis:
        container_name: bos.wiki-redis
        image: redis
        ports:
            - "6382:6379"

    nginx:
        container_name: bos.wiki-nginx
        image: nginx
        working_dir: /www
        ports:
            - "80:80"
        volumes:
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./:/www:delegated
    php:
        container_name: bow.wiki-php
        build: .
        working_dir: /www
        volumes:
            - ./:/www:delegated
            - ./php.ini:/usr/local/etc/php/php.ini
